#写MVC中访问网页的前后缀
#  mvc:
#    view:
#      prefix: /WEN-INF/jsp/
#      suffix: .jsp
#这里是配置DataSource的四大属性
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bookstore?useUnicode=true&characterEncoding=utf-8&useSSL=false&useInformationSchema=true&serverTimezone=GMT%2B8
    username:
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    #配置service包扫描
  webservices:
    path: com.zzti.bookstore.service

#thymeleaf模板设置
thymeleaf:
  prefix: classpath:/templates
  suffix: .html
  mode: HTML
  encoding: utf-8
  servlet.content-type: text/html
  #禁用cache缓存
  cache: false


server:
  port: 8081
  tomcat:
    uri-encoding: utf-8

mybatis:
  #Mybatis配置文件中的驼峰命名需要些为true
  #当引入通用Mapper(即tk.mapper)后就不需要再配驼峰命名了，通用mapper会自动引入
  configuration:
    map-underscore-to-camel-case: true
    #通过日志打印SQL语句
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
  #用于写mapper文件的地址
  #通用mapper不需要写地址只需要写一个通用mapper类即可
  mapper-locations: mapper/*.xml
  #别名包扫描
  type-aliases-package: com.zzti.bookstore.pojo
  #mapper接口需要在SpringbootMybatisApplication类上通过注解开启包扫描{@MapperScan("com.zzti.bookstore.mapper")}
  #当引入通用mapper后需要@MapperScan需要导tk.mapper下的包
  #在springboot中一般不写mapper文件除非是多表查询才会写mapper文件

#日志文件的配置
logging:
  level:
    com.zzti: debug

#分页插件基本配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params=count: countSql
